### PR TITLE
Fixed function calls, logo printing, and build dependency information in packaging. Version bump

### PR DESCRIPTION
**Pull request by ghost**
random_profile made some changes to the functions they provide and their return values. Any calls made to it from the generators have been updated. Additionally, random_profile remove the email_domains exposed in their main file, so I created a list of 50 email domains I pulled from some website.

The logo had some issues with printing due to the backslashes being seen as escape characters sometimes, fixed using rawstrings.

The build dependencies were not properly defined in the setup.cfg (was under metadata.dependencies when it should have been options.install_requires).

Made version bump to 1.1 for next release

### CODE REVIEW

**Comment by ghost** [comment]
Also there really should be a license on this so we can upload this to PyPI (https://pypi.org/)

Then it can be installed via the usual `pip install <package>`

**Comment by FatherVonTayvious** [comment]
Go to bed 😭 and how are you still working on the project. If you want you
can take full ownership of it.

**Comment by ghost** [comment]
## Go to bed 😭

I'm god fr fr unbeatable unreadable the master of the reamable.

## how are you still working on the project.

I use it. It stopped working so I fixed it and sent the changes upstream.

## If you want you can take full ownership of it.

So you're cool If I stick a license on it and upload it to PyPI? I was thinking of the GPLv3 (https://www.gnu.org/licenses/gpl-3.0.en.html)

**Comment by FatherVonTayvious** [comment]
Lmao you truly are a god at coding/programming. And sure I don't mind if
you upload a licenses and etc. And that's good to see you use it.

**Comment by ghost** [comment]
Aight LGTM!!!!!!

I'll do the license stuff later

**Pull request merged**
